#Importação de Dados

In [ ]:
# copia do banco de dados do artigo, que cita os dados deste teste
from os.path import exists
if (exists('/content/aula/') == False):
   ! git clone https://github.com/eniohandy/aula2.git
!ls
!pwd

fatal: destination path 'aula2' already exists and is not an empty directory.
aula2  sample_data
/content

In [ ]:
# muda para diretorio onde esta o arquivo de teste
%cd /content/aula2/
!pwd

/content/aula2
/content/aula2

In [ ]:
#lista os arquivos
!ls

parole.csv  README.md

O que importa nesta lista é o arquivo parole.csv (liberdade condicional)

In [ ]:
# pacotes basicos para o teste
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
dataset = pd.read_csv('parole.csv')
dataset.head(3)

,male,race,age,state,time.served,max.sentence,multiple.offenses,crime,violator
0,1,1,33.2,1,5.5,18,0,4,0
1,0,1,39.7,1,5.4,12,0,3,0
2,1,2,29.5,1,5.6,12,0,3,0

A seguir, a visualização de todo o dataset

In [ ]:
# descrição dos valores da tabela
# veja que para a maioria, médias e percentis não fazem sentido
dataset.describe()

,male,race,age,state,time.served,max.sentence,multiple.offenses,crime,violator
count,675.000000,675.000000,675.000000,675.000000,675.000000,675.000000,675.000000,675.000000,675.000000
mean,0.807407,1.423704,34.512296,2.887407,4.198074,13.056296,0.536296,2.059259,0.115556
std,0.394628,0.494511,10.351541,1.226224,1.226855,3.056797,0.499051,1.135892,0.319928
min,0.000000,1.000000,18.400000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,1.000000,1.000000,25.350000,2.000000,3.250000,12.000000,0.000000,1.000000,0.000000
50%,1.000000,1.000000,33.700000,3.000000,4.400000,12.000000,1.000000,2.000000,0.000000
75%,1.000000,2.000000,42.550000,4.000000,5.200000,15.000000,1.000000,3.000000,0.000000
max,1.000000,2.000000,67.000000,4.000000,6.000000,18.000000,1.000000,4.000000,1.000000

Todos os valores de um describe() fazem sentido?

#Aqui começa a análise via Machine Learning
Vejam que no nosso caso não foi preciso limpar a base.
Na realidade, isso NUNCA acontece

A seguir separa-se a última coluna (violator) das demais

In [ ]:
# X contém as todas as colunas, menos a última
X = dataset.iloc[:,:8].values
X[0]
y = dataset.iloc[:,8:9].values

In [ ]:
# Programa automático para dividir os dados
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print("tamanho do teste", X_test.shape)
print("tamanho do treino", X_train.shape)
print(y_test.shape)
print(y_train.shape)

tamanho do teste (169, 8)
tamanho do treino (506, 8)
(169, 1)
(506, 1)

In [ ]:
# NORMALIZAÇÃO DE DADOS
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test  = sc.fit_transform(X_test)

In [ ]:
X_test

array([[ 0.46457221,  1.1748539 , -0.29542369, ..., -0.4526105 ,
        -1.09307145, -0.22579734],
       [ 0.46457221, -0.85116966, -0.8617897 , ...,  0.80650349,
        -1.09307145, -1.07379181],
       [ 0.46457221,  1.1748539 ,  0.85650718, ...,  1.43606049,
        -1.09307145, -0.22579734],
       ...,
       [ 0.46457221, -0.85116966,  0.11735154, ...,  0.17694649,
         0.91485328, -1.07379181],
       [ 0.46457221, -0.85116966, -0.73699719, ...,  0.17694649,
         0.91485328,  1.47019159],
       [ 0.46457221,  1.1748539 ,  1.13489048, ..., -0.4526105 ,
         0.91485328, -1.07379181]])

In [ ]:
# ajuste para array 1D
y_test_1 = np.ravel(y_test)
y_test_1
y_train_1 = np.ravel(y_train)

Vamos usar o classificador KNN. Vamos variar K de 1 a 10 ?

In [ ]:
# Escolha de um classificador baseado em vizinhança (kNN onde k=5)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(5)
classifier.fit(X_train,y_train_1)

KNeighborsClassifier()

#Conclusões depois do treino

# Usando Holistic AI bias tools

In [ ]:
!pip install -q holisticai

In [ ]:
# Checking imports
# imports
from holisticai.bias.metrics import classification_bias_metrics
from holisticai.datasets import load_dataset
from holisticai.bias.plots import bias_metrics_report

In [ ]:
# Check what is inside
from holisticai.bias.metrics import false_negative_rate_diff, false_positive_rate_diff

In [ ]:
dataset.race.value_counts()

race
1    389
2    286
Name: count, dtype: int64

Nos documentos da internet aparece que 1 é branco e 2 é não branco. O que não parece fazer sentido, conhecendo a população carcerária dos EUA

parei aqui. Deu algo errado.
a ideia era criar dois arrays, group_a e group_b direto do dataset, converter em 1 e 0 e usar as métricas da HAI para ver os viés.

In [ ]:
arr = dataset.race.array
#arr = np.where(arr == 1, 0, arr)
#arr = np.where(arr == 2, 1, arr)
#dataset.race = arr
arr
#count_ones = np.count_nonzero(arr)
#count_ones

<NumpyExtensionArray>
[np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(2),
 np.int64(1), np.int64(1), np.int64(1), np.int64(2),
 ...
 np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1),
 np.int64(1), np.int64(1), np.int64(1), np.int64(1)]
Length: 675, dtype: int64

# TESTE PARIDADE

In [ ]:
dataset.head()

,male,race,age,state,time.served,max.sentence,multiple.offenses,crime,violator
0,1,1,33.2,1,5.5,18,0,4,0
1,0,1,39.7,1,5.4,12,0,3,0
2,1,2,29.5,1,5.6,12,0,3,0
3,1,1,22.4,1,5.7,18,0,1,0
4,1,2,21.6,1,5.4,12,0,1,0

In [ ]:
# imports
from holisticai.datasets import Dataset
# listar os atributos protegidos
p_attr = ['male', 'race', 'age']
target = ['violator']
X = dataset.drop(columns=target+p_attr)
y = dataset[target]
# Fazer group_a e group_b conforme o que ser quer analisar em termos de bias
group_a = pd.Series(np.where(dataset['race'] == 1, 1, 0))
group_b = pd.Series(np.where(dataset['race'] == 2, 1, 0))
# formatando no padrão Dataset da Holistic AI
group_a.value_counts()
group_b.value_counts()

0    389
1    286
Name: count, dtype: int64

In [ ]:
data = Dataset(X=X, y=y, group_a=group_a, group_b=group_b)

In [ ]:
data.data

features        X                                                         y  \
subfeatures state time.served max.sentence multiple.offenses crime violator
0               1         5.5           18                 0     4        0
1               1         5.4           12                 0     3        0
2               1         5.6           12                 0     3        0
3               1         5.7           18                 0     1        0
4               1         5.4           12                 0     1        0
..            ...         ...          ...               ...   ...      ...
670             4         4.2           16                 1     1        0
671             1         5.2           16                 0     3        0
672             1         5.7           12                 0     3        0
673             1         1.8           18                 0     1        0
674             1         6.0           12                 0     4        0

features    group_a group_b
subfeatures group_a group_b
0                 1       0
1                 1       0
2                 0       1
3                 1       0
4                 0       1
..              ...     ...
670               1       0
671               1       0
672               1       0
673               1       0
674               1       0

[675 rows x 8 columns]

In [ ]:
dataset_split = data.train_test_split(test_size=0.3)
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# train a model, do not forget to standard scale data
train = dataset_split['train']
test = dataset_split['test']

scaler = StandardScaler()
X_train_t = scaler.fit_transform(train['X'])
model = LogisticRegression(random_state=42, max_iter=500)
model.fit(X_train_t, train['y'])
X_test_t = scaler.transform(test['X'])
y_pred = model.predict(X_test_t)
# import function for batch computation
from holisticai.bias.metrics import classification_bias_metrics

In [ ]:
# set up groups, prediction array and true (aka target/label) array.
y_pred  = model.predict(X_test_t)          # prediction vector
y_true  = test['y']                        # true vector
group_a_test = test['group_a']        # group A
group_b_test = test['group_b']        # group B

In [ ]:
classification_bias_metrics(group_a_test, group_b_test, y_pred, y_true, metric_type='equal_outcome')

                       Value  Reference
Metric
Statistical Parity -0.004594          0
Disparate Impact    0.637097          1
Four Fifths Rule    0.637097          1
Cohen D            -0.046534          0
2SD Rule           -0.323090          0

In [ ]:
# The acceptable range is [0.8, 1.2]. Values below 0.8 are unfair towards group_a. Values above 1.2 are unfair towards group_b.